name: build-on-call

on:
  workflow_call:

jobs:

  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check All "run*" Files
        run: |
          for file in $(find ./root/etc -type f -name "run*"); do
            echo "Checking: $file"
            shellcheck "$file"
          done

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        architecture: [linux-arm64, linux-amd64]
    needs: [shellcheck]
    outputs:
      version: ${{ steps.prep.outputs.version }}
      branch: ${{ steps.prep.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if Architecture Exists
        id: arch-exists
        run: |
          (test -f ${{ matrix.architecture }}.Dockerfile && echo "result=ok" >> $GITHUB_OUTPUT) || echo "result=nok" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:v0.10.6

      - name: Login to docker.io
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Outputs for Next Steps
        if: (steps.arch-exists.outputs.result == 'ok')
        id: prep
        env:
          TAG: ${{ github.ref_name }}
          ARCHITECTURE: ${{ matrix.architecture }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          VERSION=$(jq -r '.version // empty' < VERSION.json)
          [[ -z ${VERSION} ]] && VERSION=$(date --utc --date=@$(git show -s --format=%ct $(git rev-parse --short HEAD)) +'%Y%m%d%H%M%S')
          BRANCH=$(jq -r '.branch // empty' < VERSION.json)
          [[ -n ${BRANCH} ]] && BRANCH=-${BRANCH}
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "title=${GITHUB_REPOSITORY}:${TAG}" >> $GITHUB_OUTPUT
          echo "revision=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${TAG}" >> $GITHUB_OUTPUT
          echo "vendor=${REPO_OWNER}" >> $GITHUB_OUTPUT
          echo "url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/master/README.md" >> $GITHUB_OUTPUT
          echo "platform=${ARCHITECTURE//-/\/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REPOSITORY}:${TAG}-${GITHUB_SHA:0:7}-${GITHUB_RUN_NUMBER}-${ARCHITECTURE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
          echo "package-version=${TAG}-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "image-stats=$(jq '.app = "'"${GITHUB_REPOSITORY/${REPO_OWNER}\//}"'" | .image = "'"${GITHUB_REPOSITORY}:${TAG}"'" | .revision = "'"${GITHUB_SHA:0:7}"'" | .version = "'"${VERSION}"'"' <<< "{}" | base64 -w 0)" >> $GITHUB_OUTPUT
          echo 'build-args<<EOF' >> $GITHUB_OUTPUT
          jq -r 'to_entries[] | [(.key | ascii_upcase),.value] | join("=")' < VERSION.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Build Image
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/build-push-action@v5
        with:
          load: true
          platforms: ${{ steps.prep.outputs.platform }}
          file: ./${{ matrix.architecture }}.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.prep.outputs.revision }}-${{ steps.prep.outputs.platform }}-testbuild
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            BUILD_ARCHITECTURE=${{ matrix.architecture }}
            PACKAGE_VERSION=${{ steps.prep.outputs.package-version }}
            IMAGE_STATS=${{ steps.prep.outputs.image-stats }}
            ${{ steps.prep.outputs.build-args }}

      - name: List Packages and Smoke Test
        if: (steps.arch-exists.outputs.result == 'ok')
        env:
          image: ${{ steps.prep.outputs.revision }}-${{ steps.prep.outputs.platform }}-testbuild
          package_version: ${{ steps.prep.outputs.package-version }}
          arch: ${{ matrix.architecture }}
        run: |
          upstream_tag=$(jq -r '.upstream_tag' < ./VERSION.json)
          upstream_image=$(jq -r '.upstream_image' < ./VERSION.json)
          if [[ ${upstream_tag} == alpine* || ${upstream_image} == alpine* ]]; then
            docker run --rm --entrypoint="" "ghcr.io/${image}" apk -vv info | sort > "${package_version}-packages.log" 2>&1
          else
            docker run --rm --entrypoint="" "ghcr.io/${image}" apt list --installed > "${package_version}-packages.log" 2>&1
          fi
          test_url=$(jq -r '.test_url' < ./VERSION.json)
          test_amd64=$(jq -r '.test_arm64' < ./VERSION.json)
          test_arm64=$(jq -r '.test_arm64' < ./VERSION.json)
          if [[ ${test_url} != null ]]; then
            [[ ${arch} == linux-amd64 ]]                                && do_test=true
            [[ ${arch} == linux-arm64 ]] && [[ ${test_arm64} == true ]] && do_test=true
          fi
          if [[ ${do_test} == true ]]; then
            docker run --network host -d --name service "ghcr.io/${image}"
            currenttime=$(date +%s); maxtime=$((currenttime+120)); while (! curl -fsSL -m 10 -b /dev/shm/cookie "${test_url}" > /dev/null) && [[ "$currenttime" -lt "$maxtime" ]]; do sleep 1; currenttime=$(date +%s); done
            docker logs service > "${package_version}-test.log" 2>&1
            curl -fsSL -m 10 -b /dev/shm/cookie "${test_url}" > /dev/null
            exit $?
          fi

      - name: Push Image
        if: (steps.arch-exists.outputs.result == 'ok')
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ steps.prep.outputs.platform }}
          file: ./${{ matrix.architecture }}.Dockerfile
          tags: |
            docker.io/${{ steps.prep.outputs.tag }}
            ghcr.io/${{ steps.prep.outputs.tag }}
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.title=${{ steps.prep.outputs.title }}
            org.opencontainers.image.revision=${{ steps.prep.outputs.revision }}
            org.opencontainers.image.source=${{ steps.prep.outputs.source }}
            org.opencontainers.image.vendor=${{ steps.prep.outputs.vendor }}
            org.opencontainers.image.url=${{ steps.prep.outputs.url }}
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            BUILD_ARCHITECTURE=${{ matrix.architecture }}
            PACKAGE_VERSION=${{ steps.prep.outputs.package-version }}
            IMAGE_STATS=${{ steps.prep.outputs.image-stats }}
            ${{ steps.prep.outputs.build-args }}

      - name: Upload Results
        continue-on-error: true
        if: always()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          name: ${{ steps.prep.outputs.package-version }}-results-${{ matrix.architecture }}
          path: |
            ${{ steps.prep.outputs.package-version }}-*.log

  publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        registry: [docker.io, ghcr.io]
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to docker.io
        if: (matrix.registry == 'docker.io')
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        if: (matrix.registry == 'ghcr.io')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifests
        uses: nick-fields/retry@v3
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          IMAGE: ${{ matrix.registry }}/${{ github.repository }}
          TAG: ${{ github.ref_name }}
          VERSION: ${{ needs.build.outputs.version }}
          BRANCH: ${{ needs.build.outputs.branch }}
        with:
          max_attempts: 3
          timeout_minutes: 5
          retry_wait_seconds: 30
          command: |
            SOURCE=${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA:0:7}-${{ github.run_number }}
            [[ -f linux-amd64.Dockerfile ]]  && AMD64=${SOURCE}-linux-amd64
            [[ -f linux-arm64.Dockerfile ]]  && ARM64=${SOURCE}-linux-arm64
            docker manifest create ${IMAGE}:${TAG}${BRANCH} ${AMD64} ${ARM64}
            docker manifest push   ${IMAGE}:${TAG}${BRANCH}
            docker manifest create ${IMAGE}:${TAG}${BRANCH}-${VERSION//\~/-} ${AMD64} ${ARM64}
            docker manifest push   ${IMAGE}:${TAG}${BRANCH}-${VERSION//\~/-}
            docker manifest create ${IMAGE}:${TAG}-${GITHUB_SHA:0:7} ${AMD64} ${ARM64}
            docker manifest push   ${IMAGE}:${TAG}-${GITHUB_SHA:0:7}
            IS_LATEST=$(jq -r '.latest // empty' < VERSION.json)
            if [[ ${IS_LATEST} == true ]]; then
              docker manifest create ${IMAGE}:latest ${AMD64} ${ARM64}
              docker manifest push   ${IMAGE}:latest
            fi
          on_retry_command: |
            docker manifest rm     ${IMAGE}:${TAG}${BRANCH} || true
            docker manifest rm     ${IMAGE}:${TAG}${BRANCH}-${VERSION//\~/-} || true
            docker manifest rm     ${IMAGE}:${TAG}-${GITHUB_SHA:0:7} || true
            IS_LATEST=$(jq -r '.latest // empty' < VERSION.json)
            if [[ ${IS_LATEST} == true ]]; then
              docker manifest rm     ${IMAGE}:latest || true
            fi

  tags:
    runs-on: ubuntu-22.04
    needs: [build, publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git Config
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
        run: |
          git config --global user.email "${GITHUB_OWNER}@users.noreply.github.com"
          git config --global user.name "${GITHUB_OWNER}"

      - name: Update "tags.json" File
        uses: nick-fields/retry@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.ref_name }}
          VERSION: ${{ needs.build.outputs.version }}
          BRANCH: ${{ needs.build.outputs.branch }}
        with:
          max_attempts: 3
          timeout_minutes: 5
          retry_wait_seconds: 30
          command: |
            TAGS="${TAG}${BRANCH},${TAG}${BRANCH}-${VERSION//\~/-},${TAG}${BRANCH}-${GITHUB_SHA:0:7}"
            LAST_UPDATED=$(date -u +'%FT%T.%3NZ')
            IS_LATEST=$(jq -r '.latest // false' < VERSION.json)
            DESCRIPTION=$(jq -r '.description // empty' < VERSION.json)
            HIDE=$(jq -r '.hide // false' < VERSION.json)
            git clone -b "master" "https://${GITHUB_TOKEN}@github.com/${REPO}.git" masterGit
            cd "${GITHUB_WORKSPACE}/masterGit" || exit 1
            if [[ ${HIDE} != true ]]; then
              [[ ! -f tags.json ]] && echo "{}" > tags.json
              tags_json=$(cat ./tags.json)
              jq '.'"${TAG}"'.tags[0] = "'"${TAG}${BRANCH}"'" | .'"${TAG}"'.tags[1] = "'"${TAG}${BRANCH}"'-'"${VERSION//\~/-}"'" | .'"${TAG}"'.tags[2] = "'"${TAG}${BRANCH}"'-'"${GITHUB_SHA:0:7}"'" | .'"${TAG}"'.last_updated = "'"${LAST_UPDATED}"'" | .'"${TAG}"'.latest = '"${IS_LATEST}"' | .'"${TAG}"'.description = "'"${DESCRIPTION}"'"' <<< "${tags_json}" | jq --sort-keys > tags.json
            fi
            git add .
            if git commit -m "Update tags.json [skip ci]"; then
              git push
            fi
            cd "${GITHUB_WORKSPACE}" || exit 1
            rm -rf "${GITHUB_WORKSPACE:?}/masterGit"

  notify:
    runs-on: ubuntu-22.04
    if: always()
    needs: [build, publish]
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TAG: ${{ github.ref_name }}
          VERSION: ${{ needs.build.outputs.version }}
          BRANCH: ${{ needs.build.outputs.branch }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          STATUS: ${{ needs.publish.result }}
        shell: bash
        run: |
          if [[ "${STATUS}" == "success" ]]; then
            COLOR="3066993"
          else
            MENTION='"content": "<@269648028502196224>",'
          fi
          if [[ -z ${COMMIT_MESSAGE} ]]; then
            COMMIT_MESSAGE="---"
          fi
          json='{
            '${MENTION}'
            "embeds": [
              {
                "title": "'${GITHUB_REPOSITORY}':'${TAG}${BRANCH}'",
                "url": "https://github.com/'${GITHUB_REPOSITORY}'/actions/runs/'${GITHUB_RUN_ID}'",
                "color": '${COLOR:-15158332}',
                "fields": [
                  {
                    "name": "Commit Message",
                    "value": "```'${COMMIT_MESSAGE//\"/\\\"}'```"
                  },
                  {
                    "name": "Commit SHA",
                    "value": "['${GITHUB_SHA:0:7}'](https://github.com/'${GITHUB_REPOSITORY}'/commit/'${GITHUB_SHA}')",
                    "inline": true
                  },
                  {
                    "name": "Version",
                    "value": "'${VERSION:----}'",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "Powered by GitHub Actions"
                },
                "timestamp": "'$(date -u +'%FT%T.%3NZ')'"
              }
            ]
          }'
          curl -fsSL --retry 5 -H "Content-Type: multipart/form-data" -F "payload_json=${json}" "${DISCORD_WEBHOOK}" > /dev/null
