name: del-file

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Delete file
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          while IFS= read -r repo; do
            while IFS= read -r branch; do
              echo "Updating ${repo}/${branch}..."
              git clone -b "${branch}" "https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${repo}.git"
              cd "${GITHUB_WORKSPACE}/${repo}" || exit 1
              rm -f tags-*.json
              git add .
              if git commit -m "Deleted file [skip ci]"; then
                git push
              fi
              cd "${GITHUB_WORKSPACE}" || exit 1
              rm -rf "${GITHUB_WORKSPACE:?}/${repo}"
            done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/repos/${GITHUB_OWNER}/${repo}/branches" | jq -r --arg BRANCH "${BRANCH}" '.[] | select(.name=="master") | .name')
          done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/users/${GITHUB_OWNER}/repos?per_page=1000" | jq -r --arg REPO "${REPO}" '.[] | select(.topics[]=="docker-image") | .name')
