name: keep-alive

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
