name: sync-files

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync files
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          while IFS= read -r repo; do
            while IFS= read -r branch; do
              echo "Updating ${REPOSITORY_OWNER}/${repo}:${branch}..."
              git clone -b "${branch}" "https://${PERSONAL_TOKEN}@github.com/${REPOSITORY_OWNER}/${repo}.git"
              cd "${repo}" || exit 1
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              ############################
              echo "Do Stuff!"
              #curl -fsSL https://raw.githubusercontent.com/hotio/base/jammyvpn/update-digests.sh > update-digests.sh
              ############################
              git add --all
              if git commit -m "FileSync Updates [skip ci]"; then
                git push
              fi
              cd .. || exit 1
              rm -rf "${repo}"
            done < <(curl -u "${REPOSITORY_OWNER}:${PERSONAL_TOKEN}" -fsSL "https://api.github.com/repos/${REPOSITORY_OWNER}/${repo}/branches" | jq -r '.[] | .name')
          done < <(curl -u "${REPOSITORY_OWNER}:${PERSONAL_TOKEN}" -fsSL "https://api.github.com/users/${REPOSITORY_OWNER}/repos?per_page=1000" | jq -r '.[] | select(.topics[]=="docker-image") | .name')
