name: sync-files

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync files
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          while IFS= read -r repo; do
            while IFS= read -r branch; do
              echo "Updating ${repo}/${branch}..."
              git clone -b "${branch}" "https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${repo}.git"
              if [[ ${branch} == "master" ]]; then
                cp "${GITHUB_WORKSPACE}/file-templates/LICENSE" "${GITHUB_WORKSPACE}/${repo}/"
                cp "${GITHUB_WORKSPACE}/file-templates/README.md" "${GITHUB_WORKSPACE}/${repo}/"
              else
                cp -a "${GITHUB_WORKSPACE}/file-templates/." "${GITHUB_WORKSPACE}/${repo}/"
              fi
              cp -a "${GITHUB_WORKSPACE}/workflow-templates/." "${GITHUB_WORKSPACE}/${repo}/"
              cd "${GITHUB_WORKSPACE}/${repo}" || exit 1
              git add -A
              if git commit -m "Updated some files [skip ci]"; then
                git push
              fi
              cd "${GITHUB_WORKSPACE}" || exit 1
              rm -rf "${GITHUB_WORKSPACE:?}/${repo}"
            done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/repos/${GITHUB_OWNER}/${repo}/branches" | jq -r '.[] | .name')
          done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/users/${GITHUB_OWNER}/repos?per_page=1000" | jq -r '.[] | select(.topics[]=="docker-image") | .name')
